source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'jquery-rails'

gem 'carrierwave'

gem 'cloudinary'

group :assets do
  gem 'uglifier'
end

# Optional - turbolinks support
#gem 'turbolinks'
#gem 'jquery-turbolinks'


